name: stockorra
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.5
  provider: ^6.1.1
  firebase_auth: ^4.17.5
  firebase_core: ^2.24.2
  intl: ^0.19.0
  fl_chart: ^0.66.1
  pdf: ^3.10.7
  path_provider: ^2.1.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - lib/assets/images/
    - lib/assets/images/stockorra_logo.png
    - lib/assets/images/house_icon.png

