name: stockorra
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  intl: ^0.20.2
  fl_chart: ^0.70.2
  provider: ^6.1.2
  font_awesome_flutter: ^10.8.0

