name: stockorra
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  provider: ^6.1.1
  intl: ^0.19.0
  pdf: ^3.10.8
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  fl_chart: ^0.66.2


flutter:
  uses-material-design: true
